import turtle
turtle.shape ('turtle')
turtle.setpos (30,70)
turtle.clear ()
turtle.color ("black", "red")
turtle.begin_fill ()
turtle.setpos (70,100)
turtle.setpos (110,70)
turtle.setpos (30,70)
turtle.end_fill ()
turtle.color ("black", "purple")
turtle.begin_fill ()
turtle.setpos (30,10)
turtle.setpos (110,10)
turtle.setpos (110,70)
turtle.end_fill ()
turtle.penup ()
turtle.setpos (-70, 70)
turtle.pendown ()
turtle.color ("black", "blue")
turtle.begin_fill ()
turtle.circle(30)
turtle.end_fill ()
turtle.setpos (-70, -10)
turtle.setpos (-50, -40)
turtle.setpos (-70, -10)
turtle.setpos (-90, -40)
turtle.penup ()
turtle.setpos (-70, 45)
turtle.pendown ()
turtle.setpos (-40, 30)
turtle.setpos (-70, 45)
turtle.setpos (-100, 30)


