import turtle
turtle.shape('turtle')
def bluetriang():
    turtle.begin_fill()
    turtle.color("black","blue")
    turtle.forward(100)
    turtle.left(120)
    turtle.forward(100)
    turtle.left(120)
    turtle.forward(100)
    turtle.left(120)
    turtle.end_fill()
def p(x,y):
    turtle.penup()
    turtle.setpos(x,y)
    turtle.pendown()
p(-50, -85)
bluetriang()
p(0, 0)
bluetriang()
p(50, 85)
bluetriang()
p(50, -85)
bluetriang()
p(150, -85)
bluetriang()
p(100, 0)
bluetriang()

